# Generated by Django 5.0.6 on 2024-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('events', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='candidate',
            field=models.ManyToManyField(to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(to='states.state'),
        ),
    ]
