# Generated by Django 5.0.6 on 2024-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('familyName', models.CharField(max_length=200)),
                ('givenName', models.CharField(max_length=200)),
                ('honorificPrefix', models.CharField(max_length=200)),
                ('honorificSuffix', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('location', models.ManyToManyField(to='states.state')),
            ],
        ),
    ]
