# Generated by Django 5.0.6 on 2024-05-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='startDate',
        ),
    ]
